version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase
      - mvn clean package -f ./HelloWorldFunction
      - mv HelloWorldFunction/target/cc-project-lambda.jar .
      - sam package --s3-bucket cc-lambda-s3-bucket --template-file template.yaml --output-template-file packaged.yaml
      - sam deploy --template-file packaged.yaml --stack-name CCLambda --capabilities CAPABILITY_IAM
