version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase
      - mvn clean package -e -f ./BlogsFunction
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml 
        --output-template-file sam-template-output.yaml 
        --s3-bucket cc-lambda-s3-bucket
    artifacts:
      - sam-template-output.yaml
