version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase
      - mvn clean package -f ./BlogsFunction
      - mv BlogsFunction/target/cc-project-lambda.jar .
  post_build:
    commands:
      - sam deploy --s3-bucket cc-lambda-s3-bucket --template-file template.yaml --stack-name CCLambda --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM --no-confirm-changeset