AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  portfolio-lambda

  Sample SAM Template for portfolio-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  BlogsGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      CacheClusterEnabled: false
      CacheClusterSize: "0.5"
      MethodSettings:
        - ResourcePath: /
          HttpMethod: GET
      Domain:
        DomainName: blog.api.k6sandeep.com
        CertificateArn: !Ref BlogApiCertificate
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: "Z05093165SS7MHO0JP43"

  BlogApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "*.api.k6sandeep.com"
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - "api.k6sandeep.com"

  BlogsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./cc-project-lambda.jar
      Handler: blogs.App::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

      Events:
        Blogs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref BlogsGatewayApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BlogsApi:
    Description: "API Gateway endpoint URL for Prod stage for Blogs function"
    Value: !Sub "https://${BlogsGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  BlogsFunction:
    Description: "Blogs Function ARN"
    Value: !GetAtt BlogsFunction.Arn
  BlogsFunctionIamRole:
    Description: "Implicit IAM Role created for Blogs function"
    Value: !GetAtt BlogsFunction.Arn
